import {
  LayoutDashboard,
  Calendar,
  Users,
  Wallet,
  Settings,
  PieChart,
  Box,
  MessageSquare,
  Video,
  ShieldAlert,
  Briefcase,
  CreditCard,
} from 'lucide-react'

export const navItems = [
  { name: 'Dashboard', path: '/', icon: LayoutDashboard },
  { name: 'Agenda', path: '/agenda', icon: Calendar },
  { name: 'Sala Virtual', path: '/sala-virtual', icon: Video },
  { name: 'Pacientes', path: '/pacientes', icon: Users },
  { name: 'Sessão Online', path: '/atendimento/nova', icon: Video },
  { name: 'Financeiro', path: '/carteira', icon: Wallet },
  { name: 'Estoque', path: '/estoque', icon: Box },
  { name: 'RH & Gestão', path: '/rh', icon: Briefcase },
  { name: 'Marketing', path: '/marketing', icon: MessageSquare },
  { name: 'Relatórios', path: '/relatorios', icon: PieChart },
  { name: 'Logs', path: '/logs', icon: ShieldAlert },
  { name: 'Meu Plano', path: '/configuracoes?tab=assinatura', icon: CreditCard },
  { name: 'Configurações', path: '/configuracoes', icon: Settings },
]
